name: Build and Push Superset Images to GHCR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_PREFIX: ghcr.io/gridtechrnd
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push superset_app
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/gridtechrnd/build-superset:latest

      - name: Build and push superset_worker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          target: worker
          tags: ghcr.io/gridtechrnd/build-superset-worker:latest

      - name: Build and push superset_worker_beat
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          target: worker-beat
          tags: ghcr.io/gridtechrnd/build-superset-worker-beat:latest
